<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Paris, Madrid">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="NXQLX208"><DocLocation><![CDATA[C:\Users\tdemijolla\Desktop\Dev\WebTutotial\AdvantageDEMO]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[AdvantageDEMO]]></DName>
<Res><![CDATA[Res8]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[31/05/2021 - 15:08:41]]></Time>
<TimeTick>1622466521</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[31/05/2021 - 15:08:41]]></Time>
<TimeTick>1622466521</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[UserMenu.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:08:41]]></Time>
<TimeTick>1622466521</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" Source="Login" SourceLine="1" >
<Disp><![CDATA[UserMenu.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["squashtf"]]></Details>
<Time><![CDATA[31/05/2021 - 15:08:43]]></Time>
<TimeTick>1622466523</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" Source="Login" SourceLine="3" >
<Disp><![CDATA[username.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["60b4d633a3c6ca3014db130a0764b88523dd35947c1de909"]]></Details>
<Time><![CDATA[31/05/2021 - 15:08:44]]></Time>
<TimeTick>1622466524</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" Source="Login" SourceLine="5" >
<Disp><![CDATA[password.SetSecure]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[sign_in_btnundefined.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:08:45]]></Time>
<TimeTick>1622466525</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="Login" SourceLine="7" >
<Disp><![CDATA[sign_in_btnundefined.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" Source="Login" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping_2]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="11" Source="Login" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[1706404]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="31/05/2021 - 15:08:36" eTime="31/05/2021 - 15:08:46" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" >
<Disp><![CDATA[Récapitulatif Login]]></Disp>
</NodeArgs>
</Action>
<Action rID="T11">
<AName><![CDATA[SelectLaptop]]></AName>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[31/05/2021 - 15:08:47]]></Time>
<TimeTick>1622466527</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[31/05/2021 - 15:08:47]]></Time>
<TimeTick>1622466527</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[LaptopsCategory.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:08:47]]></Time>
<TimeTick>1622466527</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="29" Source="SelectLaptop" SourceLine="1" >
<Disp><![CDATA[LaptopsCategory.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[HP Chromebook 14 G1(ENERGY.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:08:49]]></Time>
<TimeTick>1622466529</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="32" Source="SelectLaptop" SourceLine="3" >
<Disp><![CDATA[HP Chromebook 14 G1(ENERGY.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[save_to_cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:08:50]]></Time>
<TimeTick>1622466530</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="35" Source="SelectLaptop" SourceLine="5" >
<Disp><![CDATA[save_to_cart.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="28" Source="SelectLaptop" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="27" Source="SelectLaptop" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[1706404]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="31/05/2021 - 15:08:46" eTime="31/05/2021 - 15:08:50" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="24" >
<Disp><![CDATA[Récapitulatif SelectLaptop]]></Disp>
</NodeArgs>
</Action>
<Action rID="T17">
<AName><![CDATA[Checkout]]></AName>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[31/05/2021 - 15:08:51]]></Time>
<TimeTick>1622466531</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[31/05/2021 - 15:08:51]]></Time>
<TimeTick>1622466531</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[WebElement.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:08:51]]></Time>
<TimeTick>1622466531</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="42" Source="Checkout" SourceLine="1" >
<Disp><![CDATA[WebElement.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act3\Row0\ssf14.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[check_out_btn]]></Obj>
<Details plainTxt="False" ><![CDATA[Impossible&nbsp;d’identifier&nbsp;l’objet&nbsp;"check_out_btn"&nbsp;(de&nbsp;classe&nbsp;WebButton).<br/>Vérifiez&nbsp;que&nbsp;ces&nbsp;propriétés&nbsp;d’objet&nbsp;correspondent&nbsp;à&nbsp;un&nbsp;objet&nbsp;affiché&nbsp;dans&nbsp;l’application.]]></Details>
<Time><![CDATA[31/05/2021 - 15:09:13]]></Time>
<TimeTick>1622466553</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[check_out_btn]]></Obj>
<Details plainTxt="False" ><![CDATA[Description physique de l’objet :<br>role = button<br>Mercury Class = WebButton<br>Index = 0<br>Html Tag = BUTTON<br>_xpath = //BUTTON[@id="checkOutPopUp"]<br>|Visible = 0<br>Value = CHECKOUT  ($299.99)<br>Type = submit<br>Name = CHECKOUT  ($299.99)<br>Html Id = checkOutPopUp<br>DHTML Class = roboto-medium ng-binding<br>acc_name = <br>]]></Details>
<Time><![CDATA[31/05/2021 - 15:09:13]]></Time>
<TimeTick>1622466553</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="86" status="Warning" nType="Description" Source="Checkout" SourceLine="3" >
<Disp><![CDATA[check_out_btn]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="85" status="Failed" nType="Erreur d’exécution" Source="Checkout" SourceLine="3" >
<Disp><![CDATA[check_out_btn]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="41" status="Failed" Source="Checkout" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act3\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="40" status="Failed" Source="Checkout" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[1706404]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[31/05/2021 - 15:09:13]]></Time>
<TimeTick>1622466553</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Erreur d’exécution]]></Obj>
<Details plainTxt="False" ><![CDATA[Impossible d’identifier l’objet &quot;check_out_btn&quot; (de classe WebButton).<BR/>Vérifiez que ces propriétés d’objet correspondent à un objet affiché dans l’application.<BR/>Ligne (4) : &quot;Browser(&quot;Advantage Shopping&quot;).Page(&quot;Advantage Shopping&quot;).WebButton(&quot;check_out_btn&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[31/05/2021 - 15:09:13]]></Time>
<TimeTick>1622466553</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="88" status="Failed" Source="Checkout" SourceLine="3" >
<Disp><![CDATA[Erreur d’exécution]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf18.xml]]></Path>
<ASHilite><![CDATA[1706404]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Arrêter l’exécution]]></Obj>
<Details plainTxt="False" ><![CDATA[Exécution arrêtée par l’utilisateur.]]></Details>
<Time><![CDATA[31/05/2021 - 15:10:03]]></Time>
<TimeTick>1622466603</TimeTick>
<NodeArgs eType="General" icon="12" nRep="89" status="Information" >
<Disp><![CDATA[Arrêter l’exécution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="87" status="Failed" Source="Checkout" SourceLine="3" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf17.xml]]></Path>
<ASHilite><![CDATA[1706404]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="31/05/2021 - 15:08:50" eTime="31/05/2021 - 15:10:03" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="37" status="Failed" >
<Disp><![CDATA[Récapitulatif Checkout]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Itération AdvantageDEMO 1 (ligne 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="31/05/2021 - 15:08:32" eTime="31/05/2021 - 15:10:03" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Récapitulatif Test AdvantageDEMO]]></Disp>
</NodeArgs>
</Doc>
</Report>