<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Paris, Madrid">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="NXQLX208"><DocLocation><![CDATA[C:\Users\tdemijolla\Desktop\Dev\WebTutotial\AdvantageDEMO]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[AdvantageDEMO]]></DName>
<Res><![CDATA[Res13]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[31/05/2021 - 15:38:42]]></Time>
<TimeTick>1622468322</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[31/05/2021 - 15:38:42]]></Time>
<TimeTick>1622468322</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[UserMenu.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:38:42]]></Time>
<TimeTick>1622468322</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" Source="Login" SourceLine="1" >
<Disp><![CDATA[UserMenu.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf3.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["squashtf"]]></Details>
<Time><![CDATA[31/05/2021 - 15:38:44]]></Time>
<TimeTick>1622468324</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" Source="Login" SourceLine="3" >
<Disp><![CDATA[username.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf4.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["60b4d633a3c6ca3014db130a0764b88523dd35947c1de909"]]></Details>
<Time><![CDATA[31/05/2021 - 15:38:46]]></Time>
<TimeTick>1622468326</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" Source="Login" SourceLine="5" >
<Disp><![CDATA[password.SetSecure]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf5.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[sign_in_btnundefined.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:38:48]]></Time>
<TimeTick>1622468328</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="Login" SourceLine="7" >
<Disp><![CDATA[sign_in_btnundefined.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf6.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" Source="Login" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping_2]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf2.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="11" Source="Login" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf1.xml]]></Path>
<ASHilite><![CDATA[3083452]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="31/05/2021 - 15:38:37" eTime="31/05/2021 - 15:38:49" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="8" >
<Disp><![CDATA[Récapitulatif Login]]></Disp>
</NodeArgs>
</Action>
<Action rID="T11">
<AName><![CDATA[SelectLaptop]]></AName>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[31/05/2021 - 15:38:50]]></Time>
<TimeTick>1622468330</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[31/05/2021 - 15:38:51]]></Time>
<TimeTick>1622468331</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[LaptopsCategory.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:38:51]]></Time>
<TimeTick>1622468331</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="29" Source="SelectLaptop" SourceLine="1" >
<Disp><![CDATA[LaptopsCategory.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf9.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[HP Chromebook 14 G1(ENERGY.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:38:53]]></Time>
<TimeTick>1622468333</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="32" Source="SelectLaptop" SourceLine="3" >
<Disp><![CDATA[HP Chromebook 14 G1(ENERGY.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf10.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[save_to_cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:38:54]]></Time>
<TimeTick>1622468334</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="35" Source="SelectLaptop" SourceLine="5" >
<Disp><![CDATA[save_to_cart.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf11.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="28" Source="SelectLaptop" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf8.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="27" Source="SelectLaptop" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf7.xml]]></Path>
<ASHilite><![CDATA[3083452]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="31/05/2021 - 15:38:49" eTime="31/05/2021 - 15:38:54" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="24" >
<Disp><![CDATA[Récapitulatif SelectLaptop]]></Disp>
</NodeArgs>
</Action>
<Action rID="T17">
<AName><![CDATA[Checkout]]></AName>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[31/05/2021 - 15:39:16]]></Time>
<TimeTick>1622468356</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[31/05/2021 - 15:39:16]]></Time>
<TimeTick>1622468356</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[1]]></Obj>
<Details plainTxt="False" ><![CDATA[Impossible&nbsp;d’identifier&nbsp;l’objet&nbsp;"1"&nbsp;(de&nbsp;classe&nbsp;Link).<br/>Vérifiez&nbsp;que&nbsp;ces&nbsp;propriétés&nbsp;d’objet&nbsp;correspondent&nbsp;à&nbsp;un&nbsp;objet&nbsp;affiché&nbsp;dans&nbsp;l’application.]]></Details>
<Time><![CDATA[31/05/2021 - 15:39:16]]></Time>
<TimeTick>1622468356</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[1]]></Obj>
<Details plainTxt="False" ><![CDATA[Description physique de l’objet :<br>role = link<br>Mercury Class = Link<br>Html Tag = A<br>_xpath = //LI[normalize-space()="1"]/A[@role="link"][1]<br>|Visible = -1<br>Text = 1<br>Name = 1<br>Html Id = <br>Href = javascript:void(0)<br>DHTML Class = img<br>acc_name = <br>]]></Details>
<Time><![CDATA[31/05/2021 - 15:39:17]]></Time>
<TimeTick>1622468357</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="83" status="Warning" nType="Description" Source="Checkout" SourceLine="1" >
<Disp><![CDATA[1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="82" status="Failed" nType="Erreur d’exécution" Source="Checkout" SourceLine="1" >
<Disp><![CDATA[1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="81" status="Failed" Source="Checkout" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act3\Row0\ssf13.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="80" status="Failed" Source="Checkout" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf12.xml]]></Path>
<ASHilite><![CDATA[3083452]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[31/05/2021 - 15:39:17]]></Time>
<TimeTick>1622468357</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Erreur d’exécution]]></Obj>
<Details plainTxt="False" ><![CDATA[Impossible d’identifier l’objet &quot;1&quot; (de classe Link).<BR/>Vérifiez que ces propriétés d’objet correspondent à un objet affiché dans l’application.<BR/>Ligne (2) : &quot;Browser(&quot;Advantage Shopping&quot;).Page(&quot;Advantage Shopping&quot;).Link(&quot;1&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[31/05/2021 - 15:39:17]]></Time>
<TimeTick>1622468357</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="85" status="Failed" Source="Checkout" SourceLine="1" >
<Disp><![CDATA[Erreur d’exécution]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf17.xml]]></Path>
<ASHilite><![CDATA[3083452]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Arrêter l’exécution]]></Obj>
<Details plainTxt="False" ><![CDATA[Exécution arrêtée par l’utilisateur.]]></Details>
<Time><![CDATA[31/05/2021 - 15:39:53]]></Time>
<TimeTick>1622468393</TimeTick>
<NodeArgs eType="General" icon="12" nRep="86" status="Information" >
<Disp><![CDATA[Arrêter l’exécution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="84" status="Failed" Source="Checkout" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf16.xml]]></Path>
<ASHilite><![CDATA[3083452]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="31/05/2021 - 15:38:54" eTime="31/05/2021 - 15:39:53" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="37" status="Failed" >
<Disp><![CDATA[Récapitulatif Checkout]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Itération AdvantageDEMO 1 (ligne 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="31/05/2021 - 15:38:33" eTime="31/05/2021 - 15:39:53" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Récapitulatif Test AdvantageDEMO]]></Disp>
</NodeArgs>
</Doc>
</Report>