<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="Paris, Madrid">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="NXQLX208"><DocLocation><![CDATA[C:\Users\tdemijolla\Desktop\Dev\WebTutotial\AdvantageDEMO]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[AdvantageDEMO]]></DName>
<Res><![CDATA[Res10]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[StartUp Browser]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[31/05/2021 - 15:18:51]]></Time>
<TimeTick>1622467131</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Navigate]]></Obj>
<Details plainTxt="False" ><![CDATA[Naviguer vers http://advantageonlineshopping.com]]></Details>
<Time><![CDATA[31/05/2021 - 15:18:51]]></Time>
<TimeTick>1622467131</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="9" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Navigate]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act0\Row1\ssf5.xml]]></Path>
<ASHilite><![CDATA[1706404]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[StartUp Browser.Sync]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:18:52]]></Time>
<TimeTick>1622467132</TimeTick>
<NodeArgs eType="Replay" icon="4" nRep="11" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser.Sync]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act0\Row1\ssf6.xml]]></Path>
<ASHilite><![CDATA[1706404]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" Source="Action0" SourceLine="-1" >
<Disp><![CDATA[StartUp Browser]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act0\Row1\ssf4.xml]]></Path>
<ASHilite><![CDATA[1706404]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Action rID="T7">
<AName><![CDATA[Login]]></AName>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[31/05/2021 - 15:18:57]]></Time>
<TimeTick>1622467137</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[31/05/2021 - 15:18:58]]></Time>
<TimeTick>1622467138</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[UserMenu.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:18:58]]></Time>
<TimeTick>1622467138</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="17" Source="Login" SourceLine="1" >
<Disp><![CDATA[UserMenu.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf49.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["squashtf"]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:00]]></Time>
<TimeTick>1622467140</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="20" Source="Login" SourceLine="3" >
<Disp><![CDATA[username.Set]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf50.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[password.SetSecure]]></Obj>
<Details plainTxt="False" ><![CDATA["60b4d633a3c6ca3014db130a0764b88523dd35947c1de909"]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:01]]></Time>
<TimeTick>1622467141</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="23" Source="Login" SourceLine="5" >
<Disp><![CDATA[password.SetSecure]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf51.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[sign_in_btnundefined.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:03]]></Time>
<TimeTick>1622467143</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="26" Source="Login" SourceLine="7" >
<Disp><![CDATA[sign_in_btnundefined.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf52.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="16" Source="Login" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping_2]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act1\Row0\ssf48.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="15" Source="Login" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act1\Row0\ssf47.xml]]></Path>
<ASHilite><![CDATA[1706404]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="31/05/2021 - 15:18:52" eTime="31/05/2021 - 15:19:04" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="12" >
<Disp><![CDATA[Récapitulatif Login]]></Disp>
</NodeArgs>
</Action>
<Action rID="T14">
<AName><![CDATA[SelectLaptop]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:05]]></Time>
<TimeTick>1622467145</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:05]]></Time>
<TimeTick>1622467145</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[LaptopsCategory.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:05]]></Time>
<TimeTick>1622467145</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="33" Source="SelectLaptop" SourceLine="1" >
<Disp><![CDATA[LaptopsCategory.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf55.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[HP Chromebook 14 G1(ENERGY.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:07]]></Time>
<TimeTick>1622467147</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="36" Source="SelectLaptop" SourceLine="3" >
<Disp><![CDATA[HP Chromebook 14 G1(ENERGY.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf56.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[save_to_cart.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:08]]></Time>
<TimeTick>1622467148</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="39" Source="SelectLaptop" SourceLine="5" >
<Disp><![CDATA[save_to_cart.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf57.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="32" Source="SelectLaptop" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act2\Row0\ssf54.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="31" Source="SelectLaptop" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act2\Row0\ssf53.xml]]></Path>
<ASHilite><![CDATA[1706404]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="31/05/2021 - 15:19:04" eTime="31/05/2021 - 15:19:08" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="28" >
<Disp><![CDATA[Récapitulatif SelectLaptop]]></Disp>
</NodeArgs>
</Action>
<Action rID="T20">
<AName><![CDATA[Checkout]]></AName>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:10]]></Time>
<TimeTick>1622467150</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:10]]></Time>
<TimeTick>1622467150</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[WebElement.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:10]]></Time>
<TimeTick>1622467150</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="46" Source="Checkout" SourceLine="1" >
<Disp><![CDATA[WebElement.Click]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act3\Row0\ssf60.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[check_out_btn]]></Obj>
<Details plainTxt="False" ><![CDATA[Impossible&nbsp;d’identifier&nbsp;l’objet&nbsp;"check_out_btn"&nbsp;(de&nbsp;classe&nbsp;WebButton).<br/>Vérifiez&nbsp;que&nbsp;ces&nbsp;propriétés&nbsp;d’objet&nbsp;correspondent&nbsp;à&nbsp;un&nbsp;objet&nbsp;affiché&nbsp;dans&nbsp;l’application.]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:32]]></Time>
<TimeTick>1622467172</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[check_out_btn]]></Obj>
<Details plainTxt="False" ><![CDATA[Description physique de l’objet :<br>Mercury Class = WebButton<br>Html Tag = BUTTON<br>_xpath = //BUTTON[@id="checkOutPopUp"]<br>|Visible = 0<br>Value = CHECKOUT  ($899.97)<br>Type = submit<br>Name = CHECKOUT  ($899.97)<br>Html Id = checkOutPopUp<br>DHTML Class = roboto-medium ng-binding<br>acc_name = <br>]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:32]]></Time>
<TimeTick>1622467172</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="90" status="Warning" nType="Description" Source="Checkout" SourceLine="3" >
<Disp><![CDATA[check_out_btn]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="89" status="Failed" nType="Erreur d’exécution" Source="Checkout" SourceLine="3" >
<Disp><![CDATA[check_out_btn]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="45" status="Failed" Source="Checkout" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="Mercury.SSHWeb" >
<Path><![CDATA[ZIP::Act3\Row0\ssf59.xml]]></Path>
<ASHilite><![CDATA[10000000]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="44" status="Failed" Source="Checkout" SourceLine="1" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf58.xml]]></Path>
<ASHilite><![CDATA[1706404]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Advantage Shopping]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:32]]></Time>
<TimeTick>1622467172</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Erreur d’exécution]]></Obj>
<Details plainTxt="False" ><![CDATA[Impossible d’identifier l’objet &quot;check_out_btn&quot; (de classe WebButton).<BR/>Vérifiez que ces propriétés d’objet correspondent à un objet affiché dans l’application.<BR/>Ligne (4) : &quot;Browser(&quot;Advantage Shopping&quot;).Page(&quot;Advantage Shopping&quot;).WebButton(&quot;check_out_btn&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[31/05/2021 - 15:19:32]]></Time>
<TimeTick>1622467172</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="92" status="Failed" Source="Checkout" SourceLine="3" >
<Disp><![CDATA[Erreur d’exécution]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf64.xml]]></Path>
<ASHilite><![CDATA[1706404]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Arrêter l’exécution]]></Obj>
<Details plainTxt="False" ><![CDATA[Exécution arrêtée par l’utilisateur.]]></Details>
<Time><![CDATA[31/05/2021 - 15:20:05]]></Time>
<TimeTick>1622467205</TimeTick>
<NodeArgs eType="General" icon="12" nRep="93" status="Information" >
<Disp><![CDATA[Arrêter l’exécution]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="91" status="Failed" Source="Checkout" SourceLine="3" >
<Disp><![CDATA[Advantage Shopping]]></Disp>
<BtmPane vType="ViewerGen.SSViewerGen" >
<Path><![CDATA[ZIP::Act3\Row0\ssf63.xml]]></Path>
<ASHilite><![CDATA[1706404]]></ASHilite>
</BtmPane>
</NodeArgs>
</Step>
<Summary sTime="31/05/2021 - 15:19:08" eTime="31/05/2021 - 15:20:05" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="41" status="Failed" >
<Disp><![CDATA[Récapitulatif Checkout]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Itération AdvantageDEMO 1 (ligne 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="31/05/2021 - 15:18:50" eTime="31/05/2021 - 15:20:05" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Récapitulatif Test AdvantageDEMO]]></Disp>
</NodeArgs>
</Doc>
</Report>